stages:
  - deploy

deploy_to_s3:
  stage: deploy
  image: node:20.11.1
  script:
    - cd front
    - npm install
    - npm run build
    - apt-get update && apt-get install -y python3-pip
    - pip3 install awscli
    - aws s3 sync build/ s3://$S3_BUCKET_NAME/ --delete
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  only:
    - dev-frontend
