Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: user.handler.UserHandler
      CodeUri: C:\Users\SSAFY\Desktop\Gitmagotchi\S10P31S205\back\java\HelloWorldFunction
      Runtime: java17
      Architectures:
        - x86_64