filepath: gitmagotchi/bvh/rokoko/basic.bvh
start_frame_idx: 5
end_frame_idx: 50
groundplane_joint: LeftFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftUpLeg
    - RightUpLeg
scale: 0.025
up: +y
