filepath: gitmagotchi/bvh/rokoko/jumping.bvh
start_frame_idx: 10
end_frame_idx: 200
frame_time: 0.0333333
groundplane_joint: LeftFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftUpLeg
    - RightUpLeg
scale: 0.025
up: +y
