filepath: gitmagotchi/bvh/rokoko/stretching.bvh
start_frame_idx: 480
end_frame_idx: 630
groundplane_joint: LeftFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftUpLeg
    - RightUpLeg
scale: 0.025
up: +y
