filepath: gitmagotchi/bvh/rokoko/tell_me.bvh
start_frame_idx: 10
end_frame_idx: 983
groundplane_joint: LeftFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftUpLeg
    - RightUpLeg
scale: 0.025
up: +y
